<?php

namespace Proxies\__CG__\App\AgnBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AgnMenuLines extends \App\AgnBundle\Entity\AgnMenuLines implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'childMenuId', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'execDelete', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'execInsert', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'execParameter', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'execRead', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'execUpdate', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'lineNum', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'menusetId', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'menuId', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'programId', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'prompt');
        }

        return array('__isInitialized__', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'childMenuId', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'execDelete', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'execInsert', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'execParameter', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'execRead', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'execUpdate', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'lineNum', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'menusetId', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'menuId', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'programId', '' . "\0" . 'App\\AgnBundle\\Entity\\AgnMenuLines' . "\0" . 'prompt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AgnMenuLines $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setChildMenuId($childMenuId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChildMenuId', array($childMenuId));

        return parent::setChildMenuId($childMenuId);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildMenuId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildMenuId', array());

        return parent::getChildMenuId();
    }

    /**
     * {@inheritDoc}
     */
    public function setExecDelete($execDelete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExecDelete', array($execDelete));

        return parent::setExecDelete($execDelete);
    }

    /**
     * {@inheritDoc}
     */
    public function getExecDelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExecDelete', array());

        return parent::getExecDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setExecInsert($execInsert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExecInsert', array($execInsert));

        return parent::setExecInsert($execInsert);
    }

    /**
     * {@inheritDoc}
     */
    public function getExecInsert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExecInsert', array());

        return parent::getExecInsert();
    }

    /**
     * {@inheritDoc}
     */
    public function setExecParameter($execParameter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExecParameter', array($execParameter));

        return parent::setExecParameter($execParameter);
    }

    /**
     * {@inheritDoc}
     */
    public function getExecParameter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExecParameter', array());

        return parent::getExecParameter();
    }

    /**
     * {@inheritDoc}
     */
    public function setExecRead($execRead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExecRead', array($execRead));

        return parent::setExecRead($execRead);
    }

    /**
     * {@inheritDoc}
     */
    public function getExecRead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExecRead', array());

        return parent::getExecRead();
    }

    /**
     * {@inheritDoc}
     */
    public function setExecUpdate($execUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExecUpdate', array($execUpdate));

        return parent::setExecUpdate($execUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExecUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExecUpdate', array());

        return parent::getExecUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineNum($lineNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineNum', array($lineNum));

        return parent::setLineNum($lineNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineNum', array());

        return parent::getLineNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenusetId($menusetId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenusetId', array($menusetId));

        return parent::setMenusetId($menusetId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenusetId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenusetId', array());

        return parent::getMenusetId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMenuId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuId', array());

        return parent::getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramId($programId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramId', array($programId));

        return parent::setProgramId($programId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramId', array());

        return parent::getProgramId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrompt($prompt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrompt', array($prompt));

        return parent::setPrompt($prompt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrompt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrompt', array());

        return parent::getPrompt();
    }

}
